name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  on-nscloud-v1:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@v1
        with:
          name: 200mb
          path: 200MB.zip

      - uses: namespace-actions/download-artifact@v1
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest
