on: [workflow_dispatch]

name: demo-git-mirror

jobs:
  git-mirror:
    runs-on: [nscloud-ubuntu-22.04-amd64-2x4-with-cache, nscloud-git-mirror-5gb]
    steps:
      - name: Namespace Checkout
        uses: namespacelabs/checkout@HEAD

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: MSG="hello"
          load: true
          tags: demo/app-test:v0.0.1
          platforms: linux/amd64

      - name: Run demo image
        run: |
          docker run demo/app-test:v0.0.1
