on: [push, workflow_dispatch]

name: simple-with-matrix

jobs:
  matrix-jobs:
    strategy:
      matrix:
        platform: [
            nscloud, # Alias to amd64 runner
            nscloud-amd64, # Amd64 runner with 4 CPU and 16 GB RAM
            nscloud-ubuntu-22.04-amd64-2x4, # Custom runner shape 2 CPU 4 GB RAM
            nscloud-arm64,
            nscloud-ubuntu-22.04-arm64-2x4, # Custom runner shape 2 CPU 4 GB RAM
          ]
        args: [value1, value2, value3]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: ${{ matrix.args }}
          load: true
          tags: demo/app-${{ matrix.args }}:v0.0.1

      - name: Run demo image
        run: |
          docker run demo/app-${{ matrix.args }}:v0.0.1
